version: '3.8'
services:
  polaris:
    image: ghcr.io/gdcolon/polaris-bot:main
    container_name: polaris-bot
    restart: unless-stopped
    ports:
      - "6880:6880"
    volumes:
      - ./config.json:/app/config.json
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    networks:
      - polaris-net

  mongo:
    image: mongo:6
    container_name: polaris-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - polaris-net

networks:
  polaris-net:
    driver: bridge
